version: "3.8"
services:
  postgres:
    container_name: chatapp-postgres
    image: "postgres"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: chatapp
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
